### ISSUE TITLE
Add editable prop

### ISSUE THREAD

**Issue by pA1nD** [excalidraw/excalidraw-embed#20]
It would be great to have a prop to load excalidraw in a non-editable mode.

Creating this issue here as a follow-up on excalidraw/excalidraw#1542

Suggested general usage:
```
<Excalidraw 
  editable={false}
/>
```

### Suggested Effect:
- Hides the "Shapes" pannel (tools on the top middle)
- Hides the input to change the canvas background (top left)
- Ensures the "Selected shape actions" (left middle) is not showing up
- Does not allow to modify any element in the canvas.

**Comment by ad1992** [comment]
@pA1nD whats your exact requirement for this? When will this be useful?

One requirement where I can think of is when it's shared between for example interviewer and candidate and the interviewer want to lock the session so it's not editable or to be more specific it goes into `read-only` mode.

**Comment by guimeisang** [comment]
For example, when I share my document with others, but do not allow him to edit
@ad1992

**Comment by zekenie** [comment]
I agree this would be wonderful. In my use case, I'm looking to make sketches enabled in one part of the app, and read-only in the other.

**Comment by ad1992** [comment]
It's in the roadmap https://github.com/excalidraw/excalidraw/pull/1909. We will be picking it up soon.

**Comment by prestopasto** [comment]
I'd like to add I'm in the process of exploring integration with DokuWiki.  I would use an 'editable' prop to disable edits when you are viewing a page.  This would allow zooming/panning and general exploring of a graphic, but not editing.  Then when you are editing a page I could show the full user interface to allow changes to be made.

This would help make it obvious that you can't make changes when you are only viewing a page, keep user access permissions in tact, ect.

**Comment by dwelle** [comment]
@prestopasto I'm wondering if this use case isn't an overkill since the embed library is pretty large right now (https://bundlephobia.com/result?p=excalidraw@0.6.1) for it to be used as an interactive image viewer.

**Comment by prestopasto** [comment]
@dwelle Oof, I figured it was large, but didn't realize it was quite that big.  It very likely is overkill for this use case.

Since DokuWiki pages are stored as text files I thought it may be easiest to embed the Excalidraw data into the text file and 'hydrate' the component with initial data from there.  I haven't gotten around to coding anything yet, but from reading DokuWiki plugin docs it seems that it will be a lot harder to export an image from Excalidraw on save and embed that into the viewable page than it would be to just display an Excalidraw component.  But again, still very early stages and everything is an option right now.

**Comment by dwelle** [comment]
We're in the process of moving this component repo over to the base repo, so let's close this is favor of https://github.com/excalidraw/excalidraw/issues/1866 (that issue is primarily about collaboration but the end goal should be the same).
